# Generated by Django 5.2 on 2025-05-15 18:34

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_content_en_news_content_ru_news_content_uz_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Yangilik', 'verbose_name_plural': 'Yangiliklar'},
        ),
        migrations.AlterModelOptions(
            name='newscategory',
            options={'verbose_name': 'Yangiliklar kategoriyasi', 'verbose_name_plural': 'Yangiliklar kategoriyalari'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Teg', 'verbose_name_plural': 'Teglar'},
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='news.newscategory', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Mazmuni'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Mazmuni'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Mazmuni'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Mazmuni'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='media/news/images', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Nashr etilgan'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(to='news.tag', verbose_name='Teglar'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='news',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Kategoriya nomi'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Kategoriya nomi'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Kategoriya nomi'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='name_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Kategoriya nomi'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Teg nomi'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Teg nomi'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Teg nomi'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Teg nomi'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
    ]
