# Generated by Django 5.2 on 2025-04-13 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='is_availabel',
            new_name='is_available',
        ),
    ]
