# Generated by Django 5.2 on 2025-08-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_about_content_alter_slider_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='button_link',
            field=models.URLField(blank=True, null=True, verbose_name='Tugma havolasi'),
        ),
        migrations.AddField(
            model_name='slider',
            name='button_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='slider',
            name='short_content',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
    ]
