# Generated by Django 5.2 on 2025-04-12 17:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Gallery category',
                'verbose_name_plural': 'Gallery categories',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('image', models.ImageField(upload_to='media/gallery', verbose_name='image')),
                ('gallery_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.gallerycategory', verbose_name='gallery category')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('size', models.PositiveIntegerField(default=20, verbose_name='size')),
                ('transportation', models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable')], max_length=11)),
                ('food', models.CharField(max_length=50, verbose_name='food')),
                ('description', models.TextField(verbose_name='description')),
                ('lesson_start', models.TimeField(default='08:30', verbose_name='lesson start')),
                ('lesson_end', models.TimeField(default='16:30', verbose_name='lesson end')),
                ('num_of_pupils', models.PositiveIntegerField(verbose_name='number of pupils')),
                ('head_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_classes', to='school.teacher', verbose_name='head teacher')),
                ('teachers', models.ManyToManyField(to='school.teacher', verbose_name='teachers')),
            ],
            options={
                'verbose_name': 'class',
                'verbose_name_plural': 'classes',
            },
        ),
        migrations.CreateModel(
            name='SchoolClassImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='media/class/images', verbose_name='image')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schoolclass', verbose_name='class')),
            ],
            options={
                'verbose_name': 'class image',
                'verbose_name_plural': 'class images',
            },
        ),
    ]
