# Generated by Django 5.2 on 2025-04-12 18:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_gallerycategory_gallery_schoolclass_schoolclassimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='about',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='about teacher'),
        ),
    ]
