# Generated by Django 5.2 on 2025-05-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_gallery_title_en_gallery_title_ru_gallery_title_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='degree_type',
            field=models.CharField(choices=[('BACHELOR', 'Bachelor'), ('MASTER', 'Master'), ('PHD', 'PhD'), ('DSC', 'Doctor of Science (DSc)'), ('PROFESSOR', 'Professor'), ('ASSOCIATE_PROF', 'Associate Professor'), ('RESEARCHER', 'Senior Researcher')], default='BACHELOR', max_length=15),
        ),
    ]
