# Generated by Django 5.2 on 2025-05-15 18:22

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_teacher_degree_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='lavozim nomi')),
                ('priority', models.IntegerField(default=0, verbose_name='tartib raqami')),
                ('is_leadership', models.BooleanField(default=False, verbose_name="rahbariyat a'zosi")),
            ],
            options={
                'verbose_name': 'Lavozim',
                'verbose_name_plural': 'Lavozimlar',
                'ordering': ['priority'],
            },
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': "O'qituvchi", 'verbose_name_plural': "O'qituvchilar"},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='about',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name="O'qituvchi haqida"),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='about_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name="O'qituvchi haqida"),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='about_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name="O'qituvchi haqida"),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='about_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name="O'qituvchi haqida"),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='degree_type',
            field=models.CharField(choices=[('BACHELOR', 'Bakalavr'), ('MASTER', 'Magistr'), ('PHD', 'PhD (Fan doktori)'), ('DSC', 'Fan doktori (DSc)'), ('PROFESSOR', 'Professor'), ('ASSOCIATE_PROF', 'Dotsent'), ('RESEARCHER', 'Katta ilmiy xodim')], default='BACHELOR', max_length=15, verbose_name='Ilmiy daraja'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='experience',
            field=models.CharField(max_length=255, verbose_name='Tajriba'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='experience_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Tajriba'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='experience_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Tajriba'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='experience_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Tajriba'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='hobbies',
            field=models.ManyToManyField(to='school.hobby', verbose_name='Qiziqishlari'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(upload_to='media/accounts/teacher/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(max_length=13, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='sciences',
            field=models.ManyToManyField(to='school.science', verbose_name='Fanlar'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.position', verbose_name='Lavozim'),
        ),
    ]
