# Generated by Django 5.2 on 2025-05-15 18:29

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_position_alter_teacher_options_alter_teacher_about_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Galereya', 'verbose_name_plural': 'Galereyalar'},
        ),
        migrations.AlterModelOptions(
            name='gallerycategory',
            options={'verbose_name': 'Galereya kategoriyasi', 'verbose_name_plural': 'Galereya kategoriyalari'},
        ),
        migrations.AlterModelOptions(
            name='hobby',
            options={'verbose_name': 'Qiziqish', 'verbose_name_plural': 'Qiziqishlar'},
        ),
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'verbose_name': 'Sinf', 'verbose_name_plural': 'Sinflar'},
        ),
        migrations.AlterModelOptions(
            name='schoolclassimage',
            options={'verbose_name': 'Sinf rasmi', 'verbose_name_plural': 'Sinf rasmlari'},
        ),
        migrations.AlterModelOptions(
            name='science',
            options={'verbose_name': 'Fan', 'verbose_name_plural': 'Fanlar'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Koʻnikma', 'verbose_name_plural': 'Koʻnikmalar'},
        ),
        migrations.AlterModelOptions(
            name='teacherschedule',
            options={'verbose_name': 'Oʻqituvchi dars jadvali', 'verbose_name_plural': 'Oʻqituvchilar dars jadvallari'},
        ),
        migrations.AlterField(
            model_name='gallery',
            name='gallery_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.gallerycategory', verbose_name='Galereya kategoriyasi'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='media/gallery', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title_uz',
            field=models.CharField(max_length=128, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Kategoriya nomi'),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Kategoriya nomi'),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Kategoriya nomi'),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='name_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Kategoriya nomi'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Qiziqish nomi'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Qiziqish nomi'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Qiziqish nomi'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='name_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Qiziqish nomi'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='description_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='food',
            field=models.CharField(max_length=50, verbose_name='Ovqatlanish'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='food_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Ovqatlanish'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='food_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Ovqatlanish'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='food_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Ovqatlanish'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='head_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_classes', to='school.teacher', verbose_name='Sinf rahbari'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='lesson_end',
            field=models.TimeField(default='16:30', verbose_name='Dars tugashi'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='lesson_start',
            field=models.TimeField(default='08:30', verbose_name='Dars boshlanishi'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Sinf nomi'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Sinf nomi'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Sinf nomi'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='name_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Sinf nomi'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='num_of_pupils',
            field=models.PositiveIntegerField(verbose_name='Oʻquvchilar soni'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='size',
            field=models.PositiveIntegerField(default=20, verbose_name='Sinf hajmi'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='start_date',
            field=models.DateField(verbose_name='Boshlanish sanasi'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='teachers',
            field=models.ManyToManyField(to='school.teacher', verbose_name='Oʻqituvchilar'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='transportation',
            field=models.CharField(choices=[('AVAILABLE', 'Mavjud'), ('UNAVAILABLE', 'Mavjud emas')], max_length=11, verbose_name='Transport xizmati'),
        ),
        migrations.AlterField(
            model_name='schoolclassimage',
            name='image',
            field=models.ImageField(upload_to='media/class/images', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='schoolclassimage',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schoolclass', verbose_name='Sinf'),
        ),
        migrations.AlterField(
            model_name='science',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Fan nomi'),
        ),
        migrations.AlterField(
            model_name='science',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Fan nomi'),
        ),
        migrations.AlterField(
            model_name='science',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Fan nomi'),
        ),
        migrations.AlterField(
            model_name='science',
            name='name_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Fan nomi'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Koʻnikma nomi'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Koʻnikma nomi'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Koʻnikma nomi'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Koʻnikma nomi'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='percent',
            field=models.PositiveIntegerField(verbose_name='Foiz'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.teacher', verbose_name='Oʻqituvchi'),
        ),
        migrations.AlterField(
            model_name='teacherschedule',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='school.teacher', verbose_name='Oʻqituvchi'),
        ),
        migrations.AlterField(
            model_name='teacherschedule',
            name='time_from',
            field=models.TimeField(verbose_name='Boshlanish vaqti'),
        ),
        migrations.AlterField(
            model_name='teacherschedule',
            name='time_to',
            field=models.TimeField(verbose_name='Tugash vaqti'),
        ),
        migrations.AlterField(
            model_name='teacherschedule',
            name='weekday',
            field=models.CharField(max_length=50, verbose_name='Hafta kuni'),
        ),
        migrations.AlterField(
            model_name='teacherschedule',
            name='weekday_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Hafta kuni'),
        ),
        migrations.AlterField(
            model_name='teacherschedule',
            name='weekday_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Hafta kuni'),
        ),
        migrations.AlterField(
            model_name='teacherschedule',
            name='weekday_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Hafta kuni'),
        ),
    ]
