# Generated by Django 5.2 on 2025-05-15 18:36

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_gallery_options_alter_gallerycategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 15, 18, 36, 46, 142189, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
