# Generated by Django 5.2 on 2025-07-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_position_created_position_updated_alter_position_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='image_card',
            field=models.ImageField(null=True, upload_to='class/images/card', verbose_name='Sinf rasmi kard'),
        ),
        migrations.AlterField(
            model_name='schoolclassimage',
            name='image',
            field=models.ImageField(upload_to='class/images', verbose_name='Rasm'),
        ),
    ]
