# Generated by Django 5.2 on 2025-07-14 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_schoolclass_image_card_alter_schoolclassimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='pupil_birth_year',
            field=models.PositiveIntegerField(default=2015, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2025)], verbose_name="Yosh toifasi (tug'ilgan yil)"),
        ),
    ]
